import pytest
import time
import random
import string
from tests.utils.assertions import assert_json_response, assert_ok_true
from clients.book_client import BookClient

pytestmark = pytest.mark.regression


def _unique_comment(prefix: str = "autotest") -> str:
    """
        Utility: Generate a globally unique string for test data identification.

        This function combines a custom prefix, a millisecond timestamp, and a random
        suffix to ensure that every comment or input generated during a test run
        is unique, preventing 'duplicate entry' errors in the database.

        Args:
            prefix (str): A label to identify the source of the data (default: "autotest").

        Returns:
            str: A unique string in the format: prefix-timestamp-random (e.g., "autotest-1706172000000-abc123").
        """
    ts = int(time.time() * 1000)
    rnd = "".join(random.choices(string.ascii_lowercase + string.digits, k=6))
    return f"{prefix}-{ts}-{rnd}"


def _pick_book_id_from_search(book_client: BookClient) -> str:
    """
    Returns the first book id from the search result list.
    """
    resp = book_client.search_by_page(page_num=1, page_size=10, allow_redirects=False)
    body = assert_json_response(resp)
    assert_ok_true(body)

    data = body.get("data")
    assert isinstance(data, dict), data
    items = data.get("list")
    assert isinstance(items, list) and items, data
    book_id = items[0].get("id")
    assert book_id is not None, items[0]
    return str(book_id)


def _extract_comment_list(body: dict) -> list:
    """
        Utility: Extract the raw list of comment objects from the response body.

        Args:
            body (dict): The parsed JSON response from the comment list endpoint.

        Returns:
            list: A list of comment dictionaries.

        Raises:
            AssertionError: If the 'data' or 'list' structure is missing or malformed.
    """
    data = body.get("data")
    assert data is not None, body

    if isinstance(data, dict) and "list" in data:
        return data.get("list")

    raise AssertionError(f"Cannot parse comment list from data: {data}")


def _find_comment_in_pages(
    book_client: BookClient,
    book_id: str,
    content: str,
    max_pages: int = 5,
    page_size: int = 20,
) -> tuple:
    """
        Utility: Search for a specific comment string across multiple pages.

        This implements a 'Search & Verify' pattern to account for eventual consistency
        or high-volume data where the target comment might not be on the first page.

        Args:
            book_client: BookClient instance.
            book_id (str): The unique ID of the book.
            content (str): The unique string generated by _unique_comment().
            max_pages (int): Maximum depth of the paginated search.
            page_size (int): Number of items per request.

        Returns:
            tuple: (bool: found_status, dict: comment_object or None)
    """
    for page in range(1, max_pages + 1):
        resp = book_client.list_comment_by_page(
            book_id, page_num=page, page_size=page_size, allow_redirects=False
        )
        body = assert_json_response(resp)
        assert_ok_true(body)
        items = _extract_comment_list(body)

        for it in items:
            if isinstance(it, dict):
                text = it.get("commentContent")
                if text == content:
                    return True, it
    return False, None


@pytest.mark.xfail(
    reason="Known issue: comment feature disabled server-side (code=3001, msg='评论功能已关闭'). "
           "Mark xfail to keep CI green; remove when feature is re-enabled.",
    strict=False,
)
def test_reg_comment_add_then_visible_in_list(auth_book_client):
    """
        Regression Test: Verify Comment Write-Read Consistency.

        Logic Flow: searchByPage → addBookComment → listCommentByPage

        This test ensures the comment system's write-read path is consistent:
        1. Dynamic Book Discovery: Uses a real book ID from search to avoid hardcoded dependencies.
        2. Write Verification: Confirms the comment submission endpoint accepts valid input.
        3. Read Consistency: Validates the newly added comment appears in the paginated list.
    """
    book_id = _pick_book_id_from_search(auth_book_client)
    content = _unique_comment()

    # 1) add comment
    resp_add = auth_book_client.add_book_comment(
        book_id, content, allow_redirects=False
    )
    body_add = assert_json_response(resp_add)
    assert_ok_true(body_add)
    assert body_add.get("code") == 200

    # 2) verify comment appears in list
    found, item = _find_comment_in_pages(auth_book_client, book_id, content)
    assert found, f"Comment '{content}' not found in first 5 pages for bookId={book_id}"
    assert isinstance(item, dict)
